
[project]
name = "apstra-webtool"
version = "0.0.1"
dependencies = [
  'reactpy[fastapi]',
  'ck-apstra-api',
  'python-multipart',
]

[project.scripts]
#webtool = "webtool:hello_world"
webtool = "webtool:main"


[tool.poetry]
name = "apstra-webtool"
version = "0.0.1"
description = "Webtool for Apstra"
authors = ["Charlie Kim <kimcharli@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.13,>=3.11"
reactpy = {extras = ["fastapi"], version = "^1.0.2"}
aiohttp = "^3.9.4"
python-multipart = "^0.0.9"
ck-apstra-api = "^0.2.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
#requires = ["setuptools"]
#build-backend = "setuptools.build_meta"
